/** The five built-in themes, authored directly as app mode specs
 *  (seeds + authored overrides). Anything a theme leaves out is generated by
 *  the shared palette resolver. */

import type { AppModeSpec, ThemeDefinition } from "./source-types";

export const BUILT_IN_THEME_IDS = ["t3-chat", "grove", "ocean", "ember", "iris"] as const;

/** The mobile app's own hand-tuned palette, which is not part of the built-in library. */
export const MOBILE_DEFAULT_THEME_ID = "t3-code";

/**
 * Every palette the mobile app can render. Declared here so host-side tooling
 * (the app-store screenshot harness) can validate a requested theme without
 * importing React Native application code.
 */
export const MOBILE_THEME_IDS = [MOBILE_DEFAULT_THEME_ID, ...BUILT_IN_THEME_IDS] as const;

export type BuiltInThemeId = (typeof BUILT_IN_THEME_IDS)[number];
export type MobileThemeId = (typeof MOBILE_THEME_IDS)[number];
export type ThemeAppearance = "light" | "dark";

export const T3_CHAT_THEME: ThemeDefinition = {
  "id": "t3-chat",
  "label": "T3 Chat",
  "appearance": "light",
  "modes": {
    "light": {
      "seeds": {
        "canvas": "oklch(0.982446 0.010114 325.653)",
        "accent": "oklch(0.591646 0.217985 0.584)"
      },
      "overrides": {
        "cardBackground": "oklch(0.971835 0.012884 321.894)",
        "menuBackground": "oklch(0.971835 0.012884 321.894)",
        "toolbarBackground": "oklch(0.982446 0.010114 325.653)",
        "toolbarForeground": "oklch(0.325698 0.116116 325.037)",
        "textPrimary": "oklch(0.325698 0.116116 325.037)",
        "textSecondary": "oklch(0.494754 0.190937 354.544)",
        "textTertiary": "oklch(0.428932 0.163929 354.332)",
        "placeholder": "oklch(0.549927 0.090215 323.149)",
        "controlBackground": "oklch(0.869588 0.06751 334.899)",
        "controlForeground": "oklch(0.444777 0.134061 324.799)",
        "controlHoverBackground": "oklch(0.884525 0.041658 337.177)",
        "actionBackground": "oklch(0.591646 0.217985 0.584)",
        "actionForeground": "oklch(1 0 0)",
        "selectionBackground": "oklch(0.939552 0.024286 321.664)",
        "selectionForeground": "oklch(0.396296 0.025134 285.196)",
        "inputBorder": "oklch(0.851713 0.055822 336.6)",
        "borderSubtle": "oklch(0.923531 0.021247 328.096)",
        "focusRing": "oklch(0.591646 0.217985 0.584)",
        "high": "oklch(0.76859 0.164659 70.08)",
        "critical": "oklch(0.627117 0.248974 7.734)"
      }
    },
    "dark": {
      "seeds": {
        "canvas": "oklch(0.22813 0.020366 307.469)",
        "accent": "oklch(0.460685 0.185347 4.099)"
      },
      "overrides": {
        "cardBackground": "oklch(0.267101 0.02016 311.799)",
        "menuBackground": "oklch(0.267101 0.02016 311.799)",
        "toolbarBackground": "oklch(0.22813 0.020366 307.469)",
        "toolbarForeground": "oklch(0.980735 0.004092 301.426)",
        "textPrimary": "oklch(0.980735 0.004092 301.426)",
        "textSecondary": "oklch(0.880303 0.03077 342.696)",
        "textTertiary": "oklch(0.880303 0.03077 342.696)",
        "placeholder": "oklch(0.657087 0.028226 307.985)",
        "controlBackground": "oklch(0.313674 0.030572 310.061)",
        "controlForeground": "oklch(0.848252 0.038248 307.961)",
        "controlHoverBackground": "oklch(0.364912 0.050794 308.491)",
        "actionBackground": "oklch(0.460685 0.185347 4.099)",
        "actionForeground": "oklch(0.901233 0.057189 343.694)",
        "selectionBackground": "oklch(0.364912 0.050794 308.491)",
        "selectionForeground": "oklch(0.964695 0.009139 341.803)",
        "inputBorder": "oklch(0.266817 0.02897 344.461)",
        "borderSubtle": "oklch(0.266943 0.015262 302.425)",
        "focusRing": "oklch(0.591646 0.217985 0.584)",
        "high": "oklch(0.76859 0.164659 70.08)",
        "critical": "oklch(0.458704 0.169677 3.815)"
      }
    }
  }
};

export const GROVE_THEME: ThemeDefinition = {
  "id": "grove",
  "label": "Grove",
  "appearance": "light",
  "modes": {
    "light": {
      "seeds": {
        "canvas": "oklch(0.972369 0.005497 157.15)",
        "accent": "oklch(0.523295 0.112292 158.089)"
      },
      "overrides": {
        "cardBackground": "oklch(0.972369 0.005497 157.15)",
        "menuBackground": "oklch(0.972369 0.005497 157.15)",
        "toolbarBackground": "oklch(0.972369 0.005497 157.15)",
        "toolbarForeground": "oklch(0.222003 0.03479 328.979)",
        "textPrimary": "oklch(0.222003 0.03479 328.979)",
        "textSecondary": "oklch(0.540472 0.014944 326.176)",
        "textTertiary": "oklch(0.527266 0.012309 320.683)",
        "placeholder": "oklch(0.529681 0.01551 326.299)",
        "controlBackground": "oklch(0.936464 0.014601 163.554)",
        "controlForeground": "oklch(0.222003 0.03479 328.979)",
        "controlHoverBackground": "oklch(0.909438 0.021521 164.612)",
        "actionBackground": "oklch(0.523295 0.112292 158.089)",
        "actionForeground": "oklch(0.990339 0.008411 325.64)",
        "selectionBackground": "oklch(0.909438 0.021521 164.612)",
        "selectionForeground": "oklch(0.222003 0.03479 328.979)",
        "inputBorder": "oklch(0.829746 0.016084 168.234)",
        "borderSubtle": "oklch(0.864831 0.01312 167.255)",
        "focusRing": "oklch(0.523295 0.112292 158.089)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.637823 0.237287 25.436)"
      }
    },
    "dark": {
      "seeds": {
        "canvas": "oklch(0.260865 0.02152 162.75)",
        "accent": "oklch(0.796228 0.133058 157.319)"
      },
      "overrides": {
        "cardBackground": "oklch(0.260865 0.02152 162.75)",
        "menuBackground": "oklch(0.260865 0.02152 162.75)",
        "toolbarBackground": "oklch(0.260865 0.02152 162.75)",
        "toolbarForeground": "oklch(0.990339 0.008411 325.64)",
        "textPrimary": "oklch(0.990339 0.008411 325.64)",
        "textSecondary": "oklch(0.666747 0.004239 187.292)",
        "textTertiary": "oklch(0.715427 0.010896 171.428)",
        "placeholder": "oklch(0.739243 0.002222 223.225)",
        "controlBackground": "oklch(0.380487 0.048313 159.608)",
        "controlForeground": "oklch(0.990339 0.008411 325.64)",
        "controlHoverBackground": "oklch(0.437021 0.060312 158.962)",
        "actionBackground": "oklch(0.796228 0.133058 157.319)",
        "actionForeground": "oklch(0.222003 0.03479 328.979)",
        "selectionBackground": "oklch(0.437021 0.060312 158.962)",
        "selectionForeground": "oklch(0.990339 0.008411 325.64)",
        "inputBorder": "oklch(0.519849 0.049896 160.863)",
        "borderSubtle": "oklch(0.457475 0.044046 160.971)",
        "focusRing": "oklch(0.796228 0.133058 157.319)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.655108 0.221148 23.473)"
      }
    }
  }
};

export const OCEAN_THEME: ThemeDefinition = {
  "id": "ocean",
  "label": "Ocean",
  "appearance": "light",
  "modes": {
    "light": {
      "seeds": {
        "canvas": "oklch(0.974199 0.002856 241.597)",
        "accent": "oklch(0.536684 0.120219 247.01)"
      },
      "overrides": {
        "cardBackground": "oklch(0.974199 0.002856 241.597)",
        "menuBackground": "oklch(0.974199 0.002856 241.597)",
        "toolbarBackground": "oklch(0.974199 0.002856 241.597)",
        "toolbarForeground": "oklch(0.222003 0.03479 328.979)",
        "textPrimary": "oklch(0.222003 0.03479 328.979)",
        "textSecondary": "oklch(0.541555 0.017468 323.531)",
        "textTertiary": "oklch(0.528741 0.01828 313.823)",
        "placeholder": "oklch(0.530733 0.01795 323.79)",
        "controlBackground": "oklch(0.939254 0.01193 241.729)",
        "controlForeground": "oklch(0.222003 0.03479 328.979)",
        "controlHoverBackground": "oklch(0.91295 0.018827 241.836)",
        "actionBackground": "oklch(0.536684 0.120219 247.01)",
        "actionForeground": "oklch(0.990339 0.008411 325.64)",
        "selectionBackground": "oklch(0.91295 0.018827 241.836)",
        "selectionForeground": "oklch(0.222003 0.03479 328.979)",
        "inputBorder": "oklch(0.832939 0.017389 252.598)",
        "borderSubtle": "oklch(0.867646 0.013482 252.362)",
        "focusRing": "oklch(0.536684 0.120219 247.01)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.637823 0.237287 25.436)"
      }
    },
    "dark": {
      "seeds": {
        "canvas": "oklch(0.242641 0.024125 250.573)",
        "accent": "oklch(0.758933 0.105833 241.548)"
      },
      "overrides": {
        "cardBackground": "oklch(0.242641 0.024125 250.573)",
        "menuBackground": "oklch(0.242641 0.024125 250.573)",
        "toolbarBackground": "oklch(0.242641 0.024125 250.573)",
        "toolbarForeground": "oklch(0.990339 0.008411 325.64)",
        "textPrimary": "oklch(0.990339 0.008411 325.64)",
        "textSecondary": "oklch(0.652227 0.01149 273.31)",
        "textTertiary": "oklch(0.691936 0.016294 261.588)",
        "placeholder": "oklch(0.721641 0.010192 281.271)",
        "controlBackground": "oklch(0.358725 0.043145 244.911)",
        "controlForeground": "oklch(0.990339 0.008411 325.64)",
        "controlHoverBackground": "oklch(0.413315 0.051874 243.855)",
        "actionBackground": "oklch(0.758933 0.105833 241.548)",
        "actionForeground": "oklch(0.222003 0.03479 328.979)",
        "selectionBackground": "oklch(0.413315 0.051874 243.855)",
        "selectionForeground": "oklch(0.990339 0.008411 325.64)",
        "inputBorder": "oklch(0.500905 0.043574 244.781)",
        "borderSubtle": "oklch(0.438653 0.039496 245.44)",
        "focusRing": "oklch(0.758933 0.105833 241.548)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.655108 0.221148 23.473)"
      }
    }
  }
};

export const EMBER_THEME: ThemeDefinition = {
  "id": "ember",
  "label": "Ember",
  "appearance": "light",
  "modes": {
    "light": {
      "seeds": {
        "canvas": "oklch(0.976527 0.002685 60.725)",
        "accent": "oklch(0.552831 0.129438 44.656)"
      },
      "overrides": {
        "cardBackground": "oklch(0.976527 0.002685 60.725)",
        "menuBackground": "oklch(0.976527 0.002685 60.725)",
        "toolbarBackground": "oklch(0.976527 0.002685 60.725)",
        "toolbarForeground": "oklch(0.222003 0.03479 328.979)",
        "textPrimary": "oklch(0.222003 0.03479 328.979)",
        "textSecondary": "oklch(0.543023 0.017316 331.964)",
        "textTertiary": "oklch(0.530413 0.018453 341.181)",
        "placeholder": "oklch(0.532339 0.017796 331.748)",
        "controlBackground": "oklch(0.942267 0.01151 50.785)",
        "controlForeground": "oklch(0.222003 0.03479 328.979)",
        "controlHoverBackground": "oklch(0.916502 0.01832 49.597)",
        "actionBackground": "oklch(0.552831 0.129438 44.656)",
        "actionForeground": "oklch(0.990339 0.008411 325.64)",
        "selectionBackground": "oklch(0.916502 0.01832 49.597)",
        "selectionForeground": "oklch(0.222003 0.03479 328.979)",
        "inputBorder": "oklch(0.836213 0.017153 38.661)",
        "borderSubtle": "oklch(0.870631 0.013204 39.431)",
        "focusRing": "oklch(0.552831 0.129438 44.656)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.637823 0.237287 25.436)"
      }
    },
    "dark": {
      "seeds": {
        "canvas": "oklch(0.245899 0.019144 42.044)",
        "accent": "oklch(0.762174 0.124117 52.082)"
      },
      "overrides": {
        "cardBackground": "oklch(0.245899 0.019144 42.044)",
        "menuBackground": "oklch(0.245899 0.019144 42.044)",
        "toolbarBackground": "oklch(0.245899 0.019144 42.044)",
        "toolbarForeground": "oklch(0.990339 0.008411 325.64)",
        "textPrimary": "oklch(0.990339 0.008411 325.64)",
        "textSecondary": "oklch(0.654017 0.009505 13.287)",
        "textTertiary": "oklch(0.692479 0.015227 30.963)",
        "placeholder": "oklch(0.723533 0.008741 4.515)",
        "controlBackground": "oklch(0.361499 0.044052 49.515)",
        "controlForeground": "oklch(0.990339 0.008411 325.64)",
        "controlHoverBackground": "oklch(0.416048 0.055354 50.484)",
        "actionBackground": "oklch(0.762174 0.124117 52.082)",
        "actionForeground": "oklch(0.222003 0.03479 328.979)",
        "selectionBackground": "oklch(0.416048 0.055354 50.484)",
        "selectionForeground": "oklch(0.990339 0.008411 325.64)",
        "inputBorder": "oklch(0.503003 0.045721 49.44)",
        "borderSubtle": "oklch(0.44099 0.040202 48.807)",
        "focusRing": "oklch(0.762174 0.124117 52.082)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.655108 0.221148 23.473)"
      }
    }
  }
};

export const IRIS_THEME: ThemeDefinition = {
  "id": "iris",
  "label": "Iris",
  "appearance": "light",
  "modes": {
    "light": {
      "seeds": {
        "canvas": "oklch(0.976531 0.003855 303.226)",
        "accent": "oklch(0.525348 0.15373 294.176)"
      },
      "overrides": {
        "cardBackground": "oklch(0.976531 0.003855 303.226)",
        "menuBackground": "oklch(0.976531 0.003855 303.226)",
        "toolbarBackground": "oklch(0.976531 0.003855 303.226)",
        "toolbarForeground": "oklch(0.222003 0.03479 328.979)",
        "textPrimary": "oklch(0.222003 0.03479 328.979)",
        "textSecondary": "oklch(0.543042 0.018894 325.652)",
        "textTertiary": "oklch(0.529955 0.022319 321.556)",
        "placeholder": "oklch(0.532177 0.019333 325.784)",
        "controlBackground": "oklch(0.941387 0.014687 300.474)",
        "controlForeground": "oklch(0.222003 0.03479 328.979)",
        "controlHoverBackground": "oklch(0.914882 0.022965 299.986)",
        "actionBackground": "oklch(0.525348 0.15373 294.176)",
        "actionForeground": "oklch(0.990339 0.008411 325.64)",
        "selectionBackground": "oklch(0.914882 0.022965 299.986)",
        "selectionForeground": "oklch(0.222003 0.03479 328.979)",
        "inputBorder": "oklch(0.834773 0.023405 303.676)",
        "borderSubtle": "oklch(0.869608 0.018226 303.859)",
        "focusRing": "oklch(0.525348 0.15373 294.176)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.637823 0.237287 25.436)"
      }
    },
    "dark": {
      "seeds": {
        "canvas": "oklch(0.225975 0.031062 293.741)",
        "accent": "oklch(0.671712 0.169136 293.929)"
      },
      "overrides": {
        "cardBackground": "oklch(0.225975 0.031062 293.741)",
        "menuBackground": "oklch(0.225975 0.031062 293.741)",
        "toolbarBackground": "oklch(0.225975 0.031062 293.741)",
        "toolbarForeground": "oklch(0.990339 0.008411 325.64)",
        "textPrimary": "oklch(0.990339 0.008411 325.64)",
        "textSecondary": "oklch(0.640465 0.016197 304.171)",
        "textTertiary": "oklch(0.663321 0.025932 301.862)",
        "placeholder": "oklch(0.706249 0.014508 306.607)",
        "controlBackground": "oklch(0.325405 0.063614 294.23)",
        "controlForeground": "oklch(0.990339 0.008411 325.64)",
        "controlHoverBackground": "oklch(0.372436 0.07841 294.204)",
        "actionBackground": "oklch(0.671712 0.169136 293.929)",
        "actionForeground": "oklch(0.222003 0.03479 328.979)",
        "selectionBackground": "oklch(0.372436 0.07841 294.204)",
        "selectionForeground": "oklch(0.990339 0.008411 325.64)",
        "inputBorder": "oklch(0.46756 0.065775 296.265)",
        "borderSubtle": "oklch(0.40874 0.058536 295.893)",
        "focusRing": "oklch(0.671712 0.169136 293.929)",
        "high": "oklch(0.772406 0.172798 65.367)",
        "critical": "oklch(0.655108 0.221148 23.473)"
      }
    }
  }
};

export const BUILT_IN_THEMES: ReadonlyArray<ThemeDefinition> = [
  T3_CHAT_THEME,
  GROVE_THEME,
  OCEAN_THEME,
  EMBER_THEME,
  IRIS_THEME,
];

export function getBuiltInTheme(id: string): ThemeDefinition | null {
  return BUILT_IN_THEMES.find((theme) => theme.id === id) ?? null;
}

export function getThemeSpecForAppearance(
  theme: ThemeDefinition,
  appearance: ThemeAppearance,
): AppModeSpec | null {
  return theme.modes[appearance] ?? null;
}
