/** Regenerate src/index.css.
 *
 *  The palette contract in index.css is generated, not hand-maintained: the
 *  static `--ui-*` fallback values come from resolving the stock sources
 *  through the same resolver the app uses, and the `--local-*` context
 *  mappings come from the token manifest in ui-tokens.ts. Run:
 *
 *    node_modules/.bin/esbuild scripts/generate-ui-palette-css.ts --bundle \
 *      --platform=node --format=esm --outfile=/tmp/gen-ui-css.mjs \
 *      && node /tmp/gen-ui-css.mjs
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { resolveUiPalette } from "../src/lib/theme/resolve-ui-palette";
import { stockModeSpec } from "../src/lib/theme/stock-source";
import { paletteToCssVariables } from "../src/lib/theme/ui-palette-css";
import {
  UI_LOCAL_TOKENS,
  UI_PALETTE_VARIABLES,
  UI_SURFACE_CONTEXTS,
  uiContextVar,
} from "../src/lib/theme/ui-tokens";

const ROOT = process.cwd();
const OUT = join(ROOT, "src/index.css");

function varBlock(vars: Record<string, string>, indent = "  "): string {
  return UI_PALETTE_VARIABLES.map((name) => `${indent}${name}: ${vars[name]};`).join("\n");
}

function generatedSections(): string {
  const lightVars = paletteToCssVariables(
    resolveUiPalette(stockModeSpec("light"), "light"),
  );
  const darkVars = paletteToCssVariables(resolveUiPalette(stockModeSpec("dark"), "dark"));

  const lines: string[] = [];

  // --local-* defaults: the canvas context.
  lines.push(":root {");
  for (const token of UI_LOCAL_TOKENS) {
    lines.push(`  --local-${token}: var(--ui-canvas-${token});`);
  }
  lines.push("}");
  lines.push("");

  // Explicit surface contexts rebind --local-* to their own resolved values.
  for (const context of UI_SURFACE_CONTEXTS) {
    lines.push(`[data-ui-surface="${context}"] {`);
    for (const token of UI_LOCAL_TOKENS) {
      lines.push(`  --local-${token}: var(${uiContextVar(context, token)});`);
    }
    lines.push("}");
    lines.push("");
  }

  // Static stock fallbacks — identical to what applyUsageMonitorTheme paints
  // for the unthened look, so first paint matches post-boot exactly.
  lines.push(':root[data-theme="light"] {');
  lines.push("  color-scheme: light;");
  lines.push(varBlock(lightVars));
  lines.push("}");
  lines.push("");
  lines.push(':root[data-theme="dark"] {');
  lines.push("  color-scheme: dark;");
  lines.push(varBlock(darkVars));
  lines.push("}");
  lines.push("");
  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push('  :root:not([data-theme="light"]) {');
  lines.push("    color-scheme: dark;");
  lines.push(varBlock(darkVars, "    "));
  lines.push("  }");
  lines.push("}");

  return lines.join("\n");
}

const TEMPLATE_HEAD = `/*
 * src/index.css — generated by scripts/generate-ui-palette-css.ts.
 * Do not hand-edit; update the generator or the stock sources instead.
 *
 * Palette contract:
 *   --ui-{context}-{token}   resolved palette values (static stock fallbacks;
 *                            the theme layer overrides them at runtime)
 *   --ui-glass-* / --ui-panel-* / --ui-shadow / --ui-scrim
 *                            window material values
 *   --local-{token}          the nearest enclosing [data-ui-surface] context,
 *                            defaulting to canvas — every component utility
 *                            (bg-ui-surface, text-ui-primary, …) resolves here
 */

@import "tailwindcss";

/* ---- Resolved palette + surface contexts ---- */

`;

const THEME_BLOCK = `

/* ---- Semantic utilities ----
 * Component classes read --local-* tokens, so every usage of
 * bg-ui-surface / text-ui-* / border-ui-* follows the surface
 * context of its enclosing [data-ui-surface] element. */

@theme inline {
  /* surfaces */
  --color-ui-surface: var(--local-background);
  --color-ui-canvas: var(--ui-canvas-background);
  --color-ui-toolbar: var(--ui-toolbar-background);
  --color-ui-menu: var(--ui-menu-background);
  --color-ui-card: var(--ui-card-background);

  /* text */
  --color-ui-primary: var(--local-text-primary);
  --color-ui-secondary: var(--local-text-secondary);
  --color-ui-tertiary: var(--local-text-tertiary);
  --color-ui-placeholder: var(--local-text-placeholder);
  --color-ui-disabled: var(--local-text-disabled);
  --color-ui-accent: var(--local-accent-text);

  /* borders */
  --color-ui-subtle: var(--local-border-subtle);
  --color-ui-outline: var(--local-border-control);
  --color-ui-focus: var(--local-border-focus);

  /* neutral controls */
  --color-ui-control: var(--local-control-rest-background);
  --color-ui-control-fg: var(--local-control-rest-foreground);
  --color-ui-control-hover: var(--local-control-hover-background);
  --color-ui-control-pressed: var(--local-control-pressed-background);
  --color-ui-control-disabled: var(--local-control-disabled-background);
  --color-ui-control-disabled-fg: var(--local-control-disabled-foreground);

  /* primary + destructive actions */
  --color-ui-action: var(--local-action-rest-background);
  --color-ui-action-fg: var(--local-action-rest-foreground);
  --color-ui-action-hover: var(--local-action-hover-background);
  --color-ui-action-pressed: var(--local-action-pressed-background);
  --color-ui-action-disabled: var(--local-action-disabled-background);
  --color-ui-action-disabled-fg: var(--local-action-disabled-foreground);
  --color-ui-destructive: var(--local-destructive-rest-background);
  --color-ui-destructive-fg: var(--local-destructive-rest-foreground);
  --color-ui-destructive-hover: var(--local-destructive-hover-background);
  --color-ui-destructive-pressed: var(--local-destructive-pressed-background);
  --color-ui-destructive-disabled: var(--local-destructive-disabled-background);
  --color-ui-destructive-disabled-fg: var(--local-destructive-disabled-foreground);

  /* selection */
  --color-ui-selection: var(--local-selection-background);
  --color-ui-selection-fg: var(--local-selection-foreground);
  --color-ui-selection-hover: var(--local-selection-hover-background);
  --color-ui-selection-hover-fg: var(--local-selection-hover-foreground);

  /* inputs */
  --color-ui-input: var(--local-input-background);
  --color-ui-input-fg: var(--local-input-foreground);
  --color-ui-input-placeholder: var(--local-input-placeholder);
  --color-ui-input-border: var(--local-input-border);
  --color-ui-input-focus: var(--local-input-focus);

  /* fills + tracks */
  --color-ui-track: var(--local-track);

  /* status: filled bar, readable text, soft badge */
  --color-ui-status-healthy: var(--local-status-healthy-fill);
  --color-ui-status-healthy-text: var(--local-status-healthy-text);
  --color-ui-status-healthy-soft: var(--local-status-healthy-soft-background);
  --color-ui-status-healthy-soft-fg: var(--local-status-healthy-soft-foreground);
  --color-ui-status-warning: var(--local-status-warning-fill);
  --color-ui-status-warning-text: var(--local-status-warning-text);
  --color-ui-status-warning-soft: var(--local-status-warning-soft-background);
  --color-ui-status-warning-soft-fg: var(--local-status-warning-soft-foreground);
  --color-ui-status-high: var(--local-status-high-fill);
  --color-ui-status-high-text: var(--local-status-high-text);
  --color-ui-status-high-soft: var(--local-status-high-soft-background);
  --color-ui-status-high-soft-fg: var(--local-status-high-soft-foreground);
  --color-ui-status-critical: var(--local-status-critical-fill);
  --color-ui-status-critical-text: var(--local-status-critical-text);
  --color-ui-status-critical-soft: var(--local-status-critical-soft-background);
  --color-ui-status-critical-soft-fg: var(--local-status-critical-soft-foreground);
  --color-ui-status-neutral: var(--local-status-neutral-fill);
  --color-ui-status-neutral-text: var(--local-status-neutral-text);
  --color-ui-status-neutral-soft: var(--local-status-neutral-soft-background);
  --color-ui-status-neutral-soft-fg: var(--local-status-neutral-soft-foreground);
  --color-ui-status-info: var(--local-status-info-fill);
  --color-ui-status-info-text: var(--local-status-info-text);
  --color-ui-status-info-soft: var(--local-status-info-soft-background);
  --color-ui-status-info-soft-fg: var(--local-status-info-soft-foreground);

  /* provider identity */
  --color-ui-provider-blue: var(--local-provider-blue-background);
  --color-ui-provider-blue-fg: var(--local-provider-blue-foreground);
  --color-ui-provider-green: var(--local-provider-green-background);
  --color-ui-provider-green-fg: var(--local-provider-green-foreground);
  --color-ui-provider-orange: var(--local-provider-orange-background);
  --color-ui-provider-orange-fg: var(--local-provider-orange-foreground);

  /* window material */
  --color-ui-glass: var(--ui-glass-rest-background);
  --color-ui-glass-fg: var(--ui-glass-rest-foreground);
  --color-ui-glass-hover: var(--ui-glass-hover-background);
  --color-ui-glass-pressed: var(--ui-glass-pressed-background);
  --color-ui-glass-disabled: var(--ui-glass-disabled-background);
  --color-ui-glass-disabled-fg: var(--ui-glass-disabled-foreground);
  --color-ui-scrim: var(--ui-scrim);

  --shadow-menu: 0 8px 24px var(--ui-shadow);

  /* typography (set at runtime by appearance settings) */
  --font-sans: "SF Pro Text", "SF Pro Display", -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
  --font-mono: "SF Mono", "SFMono-Regular", Menlo, Consolas, "Liberation Mono", monospace;
}

/* ---- Base ---- */

@layer base {
  html,
  body,
  #root {
    height: 100%;
  }

  body {
    margin: 0;
    font-family: var(--font-sans);
    font-size: var(--font-size-interface, 13px);
    color: var(--ui-canvas-text-primary);
    background: transparent;
    -webkit-font-smoothing: antialiased;
    -webkit-tap-highlight-color: transparent;
    user-select: none;
    cursor: default;
  }

  /* The standalone Appearance window is opaque — it paints its own canvas. */
  html[data-window="appearance"],
  html[data-window="appearance"] body {
    background: var(--ui-menu-background);
  }

  input,
  textarea {
    user-select: text;
  }
}

/* ---- Window shell ---- */

/* A declared surface context paints its resolved background + primary text. */
.ui-surface {
  background: var(--local-background);
  color: var(--local-text-primary);
}

.app-shell {
  height: 100%;
  background: color-mix(
    in srgb,
    var(--ui-panel-tint) calc(var(--ui-panel-opacity) * 100%),
    transparent
  );
  border-radius: 16px;
  overflow: hidden;
}

[data-drag-region] {
  -webkit-app-region: drag;
}

[data-drag-region] * {
  -webkit-app-region: no-drag;
}

[data-selectable] {
  user-select: text;
}

/* ---- Glass controls (toolbar buttons over the window material) ---- */

.glass-button {
  background: var(--ui-glass-rest-background);
  color: var(--ui-glass-rest-foreground);
  box-shadow: 0 1px 2px var(--ui-shadow), inset 0 0 0 0.5px var(--ui-toolbar-border-subtle);
}

.glass-button:hover {
  background: var(--ui-glass-hover-background);
}

.glass-button:active {
  background: var(--ui-glass-pressed-background);
}

.glass-button:disabled,
.glass-button[data-disabled] {
  background: var(--ui-glass-disabled-background);
  color: var(--ui-glass-disabled-foreground);
  box-shadow: none;
}

/* ---- Fit-corner resize grip ---- */

.fit-corner {
  width: 24px;
  height: 24px;
  color: var(--ui-canvas-text-tertiary);
  opacity: 0.9;
  transition: color 120ms ease, opacity 120ms ease;
}

.fit-corner:hover {
  color: var(--ui-canvas-text-secondary);
  opacity: 1;
}

/* ---- Scrollbars ---- */

*::-webkit-scrollbar {
  width: 10px;
  height: 10px;
}

*::-webkit-scrollbar-thumb {
  background: var(--ui-canvas-control-rest-background);
  border-radius: 5px;
  border: 2.5px solid transparent;
  background-clip: padding-box;
}

*::-webkit-scrollbar-thumb:hover {
  background: var(--ui-canvas-control-hover-background);
  border: 2.5px solid transparent;
  background-clip: padding-box;
}

*::-webkit-scrollbar-track,
*::-webkit-scrollbar-corner {
  background: transparent;
}

/* ---- Text selection ---- */

::selection {
  background: var(--ui-canvas-selection-background);
  color: var(--ui-canvas-selection-foreground);
}
`;

const css = TEMPLATE_HEAD + generatedSections() + THEME_BLOCK + "\n";
writeFileSync(OUT, css);
console.log(`wrote ${OUT} (${css.split("\\n").length} lines)`);
